# Generated by Django 4.0.1 on 2022-01-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0005_alert_local_image_url_alter_alert_firebase_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='identificador',
            field=models.CharField(default=1643222875112, max_length=255),
        ),
    ]
