# Generated by Django 4.0.1 on 2022-01-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0009_alter_alert_identificador_alter_alert_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='identificador',
            field=models.CharField(default=1643376893629, max_length=255),
        ),
        migrations.AlterField(
            model_name='alert',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads1/sauron_imagens/n_avaliadas'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='slug',
            field=models.SlugField(default='alerta_1643376893629'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads1/sauron_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.IntegerField(default=1643376893),
        ),
    ]
