# Generated by Django 4.0.1 on 2022-01-30 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0015_alter_alert_identificador_alter_alert_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='camx', max_length=255)),
                ('slug', models.SlugField(default='camx')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='alert',
            name='identificador',
            field=models.CharField(default=1643574216414, max_length=255),
        ),
        migrations.AlterField(
            model_name='alert',
            name='slug',
            field=models.SlugField(default='alerta_1643574216414'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.IntegerField(default=1643574216),
        ),
        migrations.CreateModel(
            name='red_zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(default=1643574216415, max_length=255)),
                ('slug', models.SlugField(default='red_zone_<django.db.models.query_utils.DeferredAttribute object at 0x7f9580d099d0>_1643574216415')),
                ('timestamp', models.IntegerField(default=1643574216)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='example', max_length=255)),
                ('dots_txt', models.FileField(upload_to='uploads/red_zones/<django.db.models.query_utils.DeferredAttribute object at 0x7f9580d099d0>')),
                ('conteudo', models.TextField(default='nome: example, largura: 1980, altura: 1080, pontos: 574.84375,240.5625,587.84375,368.5625,676.84375,369.5625,614.84375,266.5625,')),
                ('local_dots_url', models.TextField(default='uploads/red_zones/None/red_zones_ex.txt')),
                ('alert_camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_zones', to='app_django.camera')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
