# Generated by Django 4.0.1 on 2022-01-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0016_camera_alter_alert_identificador_alter_alert_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='red_zone',
            old_name='alert_camera',
            new_name='red_zone_camera',
        ),
        migrations.AlterField(
            model_name='alert',
            name='identificador',
            field=models.CharField(default=1643574915264, max_length=255),
        ),
        migrations.AlterField(
            model_name='alert',
            name='slug',
            field=models.SlugField(default='alerta_1643574915264'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.IntegerField(default=1643574915),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='dots_txt',
            field=models.FileField(upload_to='uploads/red_zones/<django.db.models.query_utils.DeferredAttribute object at 0x7ff32c2ca9d0>'),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='identificador',
            field=models.CharField(default=1643574915265, max_length=255),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='slug',
            field=models.SlugField(default='red_zone_<django.db.models.query_utils.DeferredAttribute object at 0x7ff32c2ca9d0>_1643574915266'),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='timestamp',
            field=models.IntegerField(default=1643574915),
        ),
    ]
