# Generated by Django 4.0.1 on 2022-01-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0018_alter_alert_identificador_alter_alert_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='identificador',
            field=models.CharField(default=1643577902546, max_length=255),
        ),
        migrations.AlterField(
            model_name='alert',
            name='slug',
            field=models.SlugField(default='alerta_1643577902546'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.IntegerField(default=1643577902),
        ),
        migrations.AlterField(
            model_name='condensed_red_zones',
            name='identificador',
            field=models.CharField(default=1643577902548, max_length=255),
        ),
        migrations.AlterField(
            model_name='condensed_red_zones',
            name='red_zones_txt',
            field=models.FileField(upload_to='uploads/red_zones/<django.db.models.query_utils.DeferredAttribute object at 0x7f5cc317bbb0>/condensed'),
        ),
        migrations.AlterField(
            model_name='condensed_red_zones',
            name='slug',
            field=models.SlugField(default='condensed_red_zones_<django.db.models.query_utils.DeferredAttribute object at 0x7f5cc317bbb0>_1643577902'),
        ),
        migrations.AlterField(
            model_name='condensed_red_zones',
            name='timestamp',
            field=models.IntegerField(default=1643577902),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='dots_txt',
            field=models.FileField(upload_to='uploads/red_zones/<django.db.models.query_utils.DeferredAttribute object at 0x7f5cc317bbb0>'),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='identificador',
            field=models.CharField(default=1643577902547, max_length=255),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='slug',
            field=models.SlugField(default='red_zone_<django.db.models.query_utils.DeferredAttribute object at 0x7f5cc317bbb0>_1643577902547'),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='timestamp',
            field=models.IntegerField(default=1643577902),
        ),
    ]
