# Generated by Django 4.0.1 on 2022-01-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0019_camera_ativa_alter_alert_identificador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='identificador',
            field=models.CharField(default=1643578526307, max_length=255),
        ),
        migrations.AlterField(
            model_name='alert',
            name='slug',
            field=models.SlugField(default='alerta_1643578526307'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.IntegerField(default=1643578526),
        ),
        migrations.AlterField(
            model_name='condensed_red_zones',
            name='identificador',
            field=models.CharField(default=1643578526309, max_length=255),
        ),
        migrations.AlterField(
            model_name='condensed_red_zones',
            name='red_zones_txt',
            field=models.FileField(upload_to='uploads/red_zones/<django.db.models.query_utils.DeferredAttribute object at 0x7f9458232af0>/condensed'),
        ),
        migrations.AlterField(
            model_name='condensed_red_zones',
            name='slug',
            field=models.SlugField(default='condensed_red_zones_None_1643578526'),
        ),
        migrations.AlterField(
            model_name='condensed_red_zones',
            name='timestamp',
            field=models.IntegerField(default=1643578526),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='dots_txt',
            field=models.FileField(upload_to='uploads/red_zones/<django.db.models.query_utils.DeferredAttribute object at 0x7f9458232af0>'),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='identificador',
            field=models.CharField(default=1643578526308, max_length=255),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='slug',
            field=models.SlugField(default='red_zone_<django.db.models.query_utils.DeferredAttribute object at 0x7f9458232af0>_1643578526308'),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='timestamp',
            field=models.IntegerField(default=1643578526),
        ),
    ]
