# Generated by Django 4.0.1 on 2022-01-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0022_alter_condensed_red_zones_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='identificador',
            field=models.CharField(default=1643579727067, max_length=255),
        ),
        migrations.AlterField(
            model_name='alert',
            name='slug',
            field=models.SlugField(default='alerta_1643579727067'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.IntegerField(default=1643579727),
        ),
        migrations.AlterField(
            model_name='condensed_red_zones',
            name='identificador',
            field=models.CharField(default=1643579727068, max_length=255),
        ),
        migrations.AlterField(
            model_name='condensed_red_zones',
            name='local_dots_url',
            field=models.TextField(default='uploads/red_zones/condensed_red_zones/red_zones_x.txt'),
        ),
        migrations.AlterField(
            model_name='condensed_red_zones',
            name='red_zones_txt',
            field=models.FileField(upload_to='uploads/red_zones/condensed_red_zones'),
        ),
        migrations.AlterField(
            model_name='condensed_red_zones',
            name='slug',
            field=models.SlugField(default='red_zones_camx'),
        ),
        migrations.AlterField(
            model_name='condensed_red_zones',
            name='timestamp',
            field=models.IntegerField(default=1643579727),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='dots_txt',
            field=models.FileField(upload_to='uploads/red_zones/individual_red_zones'),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='identificador',
            field=models.CharField(default=1643579727068, max_length=255),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='local_dots_url',
            field=models.TextField(default='uploads/red_zones/camx/red_zones_x.txt'),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='slug',
            field=models.SlugField(default='red_zone_camx_1643579727068'),
        ),
        migrations.AlterField(
            model_name='red_zone',
            name='timestamp',
            field=models.IntegerField(default=1643579727),
        ),
    ]
